service: fable-alexa-guessing-game

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  alexa:
    handler: out/guessing-game/index.handler
    events:
      - alexaSkill
